package kz.kcell.app.bonus_cmdr.ws.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-12-25T17:09:04.729+06:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://ws_api.bonus_cmdr.app.kcell.kz/", name = "AuthService")
@XmlSeeAlso({ObjectFactory.class})
public interface AuthService {

    @WebMethod
    @RequestWrapper(localName = "auth", targetNamespace = "http://ws_api.bonus_cmdr.app.kcell.kz/", className = "kz.kcell.app.bonus_cmdr.ws.stub.Auth")
    @ResponseWrapper(localName = "authResponse", targetNamespace = "http://ws_api.bonus_cmdr.app.kcell.kz/", className = "kz.kcell.app.bonus_cmdr.ws.stub.AuthResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Boolean auth(
        @WebParam(name = "user", targetNamespace = "")
        java.lang.String user,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );
}
