package kz.kcell.vaadin.ui;

/**
 * @author Pavel.Terechshenkov@kcell.kz
 * @since 18 09 2014
 */
public enum EventType {
    LOGIN_SUCCESFULL,
    LOGIN_FAILED,
    LOGOUT_SUCCESS,
    PRODUCT_SELECTED,
    EXIT,
    START_SESSION,
    SHOW_PRODUCT_SCREEN,
    SHOW_LOGIN_SCREEN,
    SHOW_PRODUCT_DESC,
    SHOW_LOGOUT_SCREEN,
    SHOW_SUBSCRIBE_LOG_SCREEN,
    SHOW_TRANSFER_BONUS_SCREEN,
    SUBSCRIBE_SERVICE,
    TRANSFER_BONUS_SUCCESS,
    TRANSLATE,
    UPDATE_BALANCE,
    ENTER_SUBSCRIBE_IVR_VIEW_IMPOSSIBLE,
    ENTER_SUBSCRIBE_IVR_FORM_IMPOSSIBLE,
    BLOCK_CAPTCHA,
//    AFTER_VIEW_CHANGE,
//    BEFORE_VIEW_CHANGE,
    CAPCTHA_PASS
}





